#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1666883056                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : en                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://pierreboudoin.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Introducing Momenti, the app that will take you on a trip down memory lane every time you open it!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Pierre Boudoin                                
your_link                                 : https://pierreboudoin.com                     
your_city                                 : Bordeaux                                
email_address                             : pierre.boudoin@gmail.com
facebook_username                         :                                           
instagram_username                        : pboudoin
twitter_username                          : pboudoin
github_username                           : pboudoin
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Children phrases and words tracker
    description                           : "With Momenti, you can log and save all those precious quotes that your children come up with, from the silly to the profound. Imagine being able to recall the exact age and stage of your child when they said something that made you laugh, or made you cry."
    fontawesome_icon_name                 : pen-nib
    
  - title                                 : iCloud sync 
    description                           : All of your data is synced to your iCloud space and is therefore available on all of your iOS devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Favorites
    description                           : "You can add your favorite quotes to your favorites list and access them easily whenever you need a pick-me-up or a reminder of how special your children are."
    fontawesome_icon_name                 : heart

  - title                                 : Share
    description                           : Share this memory with others using a beautiful template card.
    fontawesome_icon_name                 : arrow-up-from-bracket

  - title                                 : Widgets
    description                           : "if you're feeling a little nostalgic, our Home Screen widget will give you a random quote from your collection. It's like having a little piece of your children with you all the time, right on your phone's home screen."
    fontawesome_icon_name                 : square-plus

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#00A9C6"
topbar_transparency                       : 1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#C24D67"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FFFFFF"
feature_icons_background_color            : "#C24D67"

social_icons_foreground_color             : "#FFFFFF"
social_icons_background_color             : "#C24D67"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
